version: '3.8'

services:
  api:
    build: .
    container_name: shirt_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/shirt_db
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    networks:
      - shirt_network

  mongodb:
    image: mongo:5.0-focal
    container_name: shirt_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shirt_network
    # Reduce MongoDB memory usage
    command: mongod --wiredTigerCacheSizeGB 0.5

networks:
  shirt_network:
    driver: bridge

volumes:
  mongo_data:
